"""Full-model fp32 reference forward of Maverick from the UD-Q4_K_XL GGUF,
validated layer-by-layer against a llama-eval-callback log of the SAME weights.

This is the M2/M3 de-risk: it implements, in plain numpy, every semantic the
48-layer proof builder needs — GQA (40 q / 8 kv heads, 5× replication),
RoPE θ from the file's metadata with the NoPE skip on every 4th layer, the
dense/MoE interleave, input-side sigmoid top-1 routing, shared expert, final
norm + LM head — and reports where (if anywhere) it diverges from llama.cpp's
own forward. Also harvests per-layer router-logit and activation magnitudes
(sizes the proof's sigmoid table and field-fit scales).

GGUF q/k weights are stored PERMUTED (convert_hf_to_gguf's LlamaModel
permute, paired with ggml's adjacent-pair rope); we un-permute and apply
HF-style rotate-half rope, which is the convention the proof's RoPEClaim
uses. A layer-0 mismatch would expose a convention error immediately.

Run on the H100 (CPU, ~15-20 min, peak ~10 GB):
    ~/miniconda3/bin/python maverick_full_ref.py \
        --gguf ~/maverick-gguf/UD-Q4_K_XL --eval-log /tmp/m0_eval.log
"""
import argparse
import glob
import os
import re
import sys

import numpy as np

NOPE_STEP = 4              # llama.cpp LLM_ARCH_LLAMA4: rope unless (il+1) % 4 == 0


def build_index(gguf_path):
    from gguf import GGUFReader
    paths = sorted(glob.glob(os.path.join(gguf_path, "*.gguf"))) \
        if os.path.isdir(gguf_path) else [gguf_path]
    by_name, kv = {}, {}
    for p in paths:
        r = GGUFReader(p)
        for t in r.tensors:
            by_name[t.name] = t
        for f in r.fields.values():
            try:
                kv[f.name] = f.contents()
            except Exception:
                pass
    return by_name, kv


def fetch(by_name, name, rows=None):
    """Dequantize tensor `name`; `rows` (list) slices the RAW leading dim first
    (token rows of the embedding, expert slabs of the stacked MoE tensors)."""
    from gguf.quants import dequantize
    t = by_name[name]
    data = t.data
    if rows is not None:
        data = data[np.asarray(rows, dtype=np.int64)]
    return dequantize(data, t.tensor_type).astype(np.float32)


def unpermute(w, n_head):
    """Inverse of convert_hf_to_gguf LlamaModel.permute (GGUF → HF q/k layout)."""
    d_out = w.shape[0]
    return (w.reshape(n_head, d_out // n_head // 2, 2, *w.shape[1:])
             .swapaxes(1, 2).reshape(w.shape))


def rms_norm(x, w, eps):
    return x / np.sqrt((x ** 2).mean(-1, keepdims=True) + eps) * w


def rope(q, theta):
    """HF rotate-half on (T, H, Dh)."""
    T, H, Dh = q.shape
    inv = 1.0 / theta ** (np.arange(0, Dh, 2) / Dh)
    ang = np.arange(T)[:, None] * inv[None, :]          # (T, Dh/2)
    cos, sin = np.cos(ang)[:, None, :], np.sin(ang)[:, None, :]
    q1, q2 = q[..., :Dh // 2], q[..., Dh // 2:]
    return np.concatenate([q1 * cos - q2 * sin, q2 * cos + q1 * sin], -1)


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def _silu(x):
    return x * _sigmoid(x)


def _samples(log, name, k=6):
    """ggml's debug printer emits the FIRST 3 and LAST 3 elements of each row;
    returns those 6 values for the first row (token 0)."""
    m = re.search(rf"(?:ggml_debug|common_debug_cb_eval):\s+{re.escape(name)} = "
                  rf".*?\n(.*?)\n\s*sum\s*=", log, re.S)
    if not m:
        return None
    first_row = re.search(r"\[([^\[\]]+)\]", m.group(1))
    if not first_row:
        return None
    vals = re.findall(r"-?\d+\.\d+", first_row.group(1))
    return [float(v) for v in vals[:k]] or None


def _ends(vec, n=3):
    """First n + last n entries of a vector — ggml's sampling convention."""
    return np.concatenate([vec[:n], vec[-n:]])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gguf", default=os.path.expanduser("~/maverick-gguf/UD-Q4_K_XL"))
    ap.add_argument("--eval-log", default="/tmp/m0_eval.log")
    ap.add_argument("--tokens", default=None, help="comma ids; default: from log")
    ap.add_argument("--continuation", default=None,
                    help="comma ids GENERATED by the Q4 deployment (e.g. "
                         "llama.cpp greedy); compute the unexplained-info "
                         "estimate U = Σ −log2 softmax_fp32(o_i) over them")
    a = ap.parse_args()
    log = open(a.eval_log, errors="replace").read() if os.path.exists(a.eval_log) else ""

    by_name, kv = build_index(a.gguf)
    g = lambda k: kv[f"llama4.{k}"]
    L, d = g("block_count"), g("embedding_length")
    H, Hkv, Dh = g("attention.head_count"), g("attention.head_count_kv"), g("attention.key_length")
    theta, eps = g("rope.freq_base"), g("attention.layer_norm_rms_epsilon")
    print(f"model: L={L} d={d} H={H}/{Hkv} Dh={Dh} θ={theta} eps={eps:.2e}")

    if a.tokens:
        ids = [int(v) for v in a.tokens.split(",")]
    else:
        m = re.search(r"inp_tokens.*?\n.*?\[ *([-\d ,.]+)", log)
        assert m, "token ids not found in log — pass --tokens"
        ids = [int(float(v)) for v in re.findall(r"-?[\d.]+", m.group(1))]
    cont = [int(v) for v in a.continuation.split(",")] if a.continuation else []
    ids = ids + cont
    print(f"tokens: {ids}" + (f"  (last {len(cont)} = Q4 continuation)" if cont else ""))
    T = len(ids)

    x = fetch(by_name, "token_embd.weight", rows=ids)            # (T, d)
    causal = np.tril(np.ones((T, T), bool))
    stats = []
    for il in range(L):
        p = f"blk.{il}."
        h = rms_norm(x, fetch(by_name, p + "attn_norm.weight"), eps)
        wq = unpermute(fetch(by_name, p + "attn_q.weight"), H)
        wk = unpermute(fetch(by_name, p + "attn_k.weight"), Hkv)
        q = (h @ wq.T).reshape(T, H, Dh)
        k = (h @ wk.T).reshape(T, Hkv, Dh)
        v = (h @ fetch(by_name, p + "attn_v.weight").T).reshape(T, Hkv, Dh)
        if (il + 1) % NOPE_STEP != 0:
            q, k = rope(q, theta), rope(k, theta)
        k = np.repeat(k, H // Hkv, axis=1)                       # GQA 5×
        v = np.repeat(v, H // Hkv, axis=1)
        sc = np.einsum("thd,shd->hts", q, k) / np.sqrt(Dh)
        sc = np.where(causal[None], sc, -np.inf)
        w = np.exp(sc - sc.max(-1, keepdims=True))
        w /= w.sum(-1, keepdims=True)
        att = np.einsum("hts,shd->thd", w, v).reshape(T, H * Dh)
        x = x + att @ fetch(by_name, p + "attn_output.weight").T

        h = rms_norm(x, fetch(by_name, p + "ffn_norm.weight"), eps)
        if il % 2 == 1:                                          # MoE (odd layers)
            router = fetch(by_name, p + "ffn_gate_inp.weight")
            logits = h @ router.T
            e_star = logits.argmax(1)
            s = _sigmoid(logits[np.arange(T), e_star])
            chosen = sorted(set(int(e) for e in e_star))
            slab = {e: i for i, e in enumerate(chosen)}
            gw = fetch(by_name, p + "ffn_gate_exps.weight", rows=chosen)
            uw = fetch(by_name, p + "ffn_up_exps.weight", rows=chosen)
            dw = fetch(by_name, p + "ffn_down_exps.weight", rows=chosen)
            ffn = np.empty_like(x)
            for t in range(T):
                xw = s[t] * h[t]
                i = slab[int(e_star[t])]
                ffn[t] = (_silu(xw @ gw[i].T) * (xw @ uw[i].T)) @ dw[i].T
            ffn += (_silu(h @ fetch(by_name, p + "ffn_gate_shexp.weight").T)
                    * (h @ fetch(by_name, p + "ffn_up_shexp.weight").T)) \
                @ fetch(by_name, p + "ffn_down_shexp.weight").T
            stats.append((il, float(np.abs(logits).max()), float(np.abs(x).max())))
        else:                                                    # dense
            ffn = (_silu(h @ fetch(by_name, p + "ffn_gate.weight").T)
                   * (h @ fetch(by_name, p + "ffn_up.weight").T)) \
                @ fetch(by_name, p + "ffn_down.weight").T
        x = x + ffn

        ref = _samples(log, f"l_out-{il}")
        if ref:
            mine = _ends(x[0]) if len(ref) == 6 else x[0, :len(ref)]
            rel = float(np.abs(mine - ref).max() / (np.abs(ref).max() + 1e-9))
            # llama.cpp's CPU path quantizes activations to Q8 and does integer
            # dot products, so a few % per-layer drift vs fp32 is inherent and
            # COMPOUNDS over 48 layers. Tiers are informational; the meaningful
            # verdict is the final logits + top-1 agreement.
            tag = "OK " if rel < 5e-2 else ("DRIFT" if rel < 0.3 else "DIVERGED")
            print(f"  l_out-{il:02d} rel={rel:.4f} {tag}  mine={np.round(mine,4).tolist()} ref={ref}",
                  flush=True)
        else:
            print(f"  l_out-{il:02d} (no ref sample in log)", flush=True)

    xf = rms_norm(x, fetch(by_name, "output_norm.weight"), eps)
    logits = xf @ fetch(by_name, "output.weight").T
    ref = _samples(log, "result_output")
    if ref:
        mine_l = _ends(logits[0]) if len(ref) == 6 else logits[0, :len(ref)]
        rel = float(np.abs(mine_l - ref).max() / (np.abs(ref).max() + 1e-9))
        print(f"result_output rel={rel:.4f} {'OK' if rel < 2e-2 else 'DIVERGED'}")
    print(f"top-1 next token id: {int(logits[-1].argmax())}")
    if cont:
        # U(O) ≤ −Σ log2 Q(o_i | o_<i): Q = plain softmax of the fp32 reference
        # logits (a simple admissible predictor; the proof's logit-noise model
        # would only tighten this). O = the Q4 deployment's greedy tokens.
        print("\nUnexplained-info estimate (predictor = fp32 ref, outputs = Q4 greedy):")
        total, matches = 0.0, 0
        for j, tok in enumerate(cont):
            pos = len(ids) - len(cont) + j - 1          # logits that predict tok
            l = logits[pos] - logits[pos].max()
            logp = l[tok] - np.log(np.exp(l).sum())
            bits = -logp / np.log(2)
            am = int(logits[pos].argmax())
            matches += (am == tok)
            total += bits
            print(f"  pos {pos+1}: o={tok} surprisal={bits:7.3f} bits "
                  f"(fp32 top-1={am}{' MATCH' if am == tok else ''})")
        print(f"  U_total = {total:.2f} bits over {len(cont)} tokens "
              f"({total/len(cont):.3f} bits/token; greedy agreement "
              f"{matches}/{len(cont)})")
    print("\nMoE layer stats (sigmoid-table + field-fit data):")
    print("  layer  max|router logit|  max|resid|")
    for il, lr, xr in stats:
        print(f"  {il:5d}  {lr:17.3f}  {xr:11.3f}")


if __name__ == "__main__":
    main()
